# Generated by Django 4.2.11 on 2024-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('symptoms', models.TextField()),
                ('predicted_disease', models.CharField(max_length=100)),
                ('dis_des', models.TextField()),
                ('precautions', models.TextField()),
                ('medications', models.TextField()),
                ('rec_diet', models.TextField()),
                ('workout', models.TextField()),
            ],
        ),
    ]
